### ISSUE TITLE
Integration of dynamic turn time

### ISSUE THREAD

**Issue by knarfi** [IcyPalm/Hanze-TwoPlayerGameServer#16]
Currently every game has a fixed turn duration. Currently this is 10 seconds but 2 seconds were being discussed on the meetings. I think it would be good to add the option to select the turn time (or timeout time if you like). This should be integrated into the `C: challenge "<player>" "<gametype>"` command, it will become `C: challenge "<player>" "<gametype> <turn time in seconds>"`. The player that receives the challenge should be able to see this like so `SVR GAME CHALLENGE {CHALLENGER: <player>, GAMETYPE: <gametype>, TURNTIME<turn time in seconds>, CHALLENGENUMBER: <challangenumber>}`.

**Comment by KvdV96** [comment]
The turn duration should depend on whether the player is human (10 seconds) or AI (2 seconds). Correct me if I'm wrong.

**Comment by knarfi** [comment]
But the server does not know if its a human or AI. It just gets the move from the client.

**Comment by johankladder** [comment]
This might be a good idea, as 'human' player would probably think longer than 10 second about a move. The thing with playing with an AI opponent is:

- AI is faster than the 60 seconds probably, so the 'human' player can play directly after the AI's turn.

The thing is, you're right about the turning time being to short for human players. But it can be fixed by setting the turn time in the settings.conf to 60 seconds for example.

**Comment by johankladder** [comment]
@knarfi ,

I've sended a pull request for this feature. Don't know if you can see it, otherwise you can look at my version. It's included in the branch -> feature/turntimefix

**Comment by IcyPalm** [comment]
Closed with #23
