### ISSUE TITLE
New protocol doc

### ISSUE THREAD

**Issue by johankladder** [IcyPalm/Hanze-TwoPlayerGameServer#28]
Just had some problems with my git.

How do I get the new markdown protocol.md in my local branch. Im creating a feature for making the turntime variable, so i would like to change that list if that request is going through xD

**Comment by roffel** [comment]
https://help.github.com/articles/syncing-a-fork/

**Comment by johankladder** [comment]
hero.

**Comment by roffel** [comment]
Just use your search engine ;)  I used "update fork".

**Comment by johankladder** [comment]
Annnnnnnd i pushed to master xd

**Comment by goto-bus-stop** [comment]
You did push to your _own_ master branch at https://github.com/johankladder/Hanze-TwoPlayerGameServer/commits/master for #22, which is why that branch history is a bit funny now, with both this squashed merge commit and your separate commits.

You can fix that from the command line by doing:
```
git branch -f master upstream/master
git push -f origin master
```
…which will `-f`orce your own master branch to be exactly the same as the upstream master, and then overwrite (force-push) your own master branch on Github.

(I'm not sure how it works in Git UIs or IDEs)

**Comment by johankladder** [comment]
Thanks!

**Comment by IcyPalm** [comment]
This seems fixed, closing
